version: '3'

name: ft

services:

  nginx:
    build: ./requirements/nginx
    image: nginx:skoh
    restart: always
    depends_on: [wordpress]
    networks:
      wordpressnet:
        aliases: [$DOMAIN]
        # ^ https://github.com/containers/podman-compose/issues/88
    ports: ["443:443"]
    volumes:
      - wordpress_files:/wordpress:ro
    environment:
      SSL_DOMAIN: $DOMAIN

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:skoh
    restart: always
    depends_on: [mariadb]
    networks: [wordpressnet]
    volumes:
      - wordpress_files:/wordpress
    environment:
      DB_HOST: mariadb
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_USER_PASS: $DB_USER_PASS
      DOMAIN: $DOMAIN
      WP_TITLE: $WP_TITLE
      WP_ADMIN: $WP_ADMIN
      WP_PASS: $WP_PASS
      WP_EMAIL: $WP_EMAIL
      WP_USER: $WP_USER
      WP_USER_PASS: $WP_USER_PASS
      WP_USER_EMAIL: $WP_USER_EMAIL
      REDIS_HOST: redis
      REDIS_PASS: $REDIS_PASS

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:skoh
    restart: always
    networks: [wordpressnet]
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      INIT_DB_ROOT_PASS: $DB_ROOT_PASS
      INIT_DB_NAME: $DB_NAME
      INIT_DB_USER: $DB_USER
      INIT_DB_USER_PASS: $DB_USER_PASS

  ##################### BONUS #####################

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:skoh
    restart: always
    networks: [wordpressnet]
    ports: ["88:8000"]
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  redis:
    build: ./requirements/bonus/redis
    image: redis:skoh
    restart: always
    networks: [wordpressnet]
    environment:
      REDIS_PASS: $REDIS_PASS

  redis-commander:
    build: ./requirements/bonus/redis-commander
    image: redis-commander:skoh
    restart: always
    networks: [wordpressnet]
    depends_on: [redis]
    ports: ["99:8000"]
    environment:
      REDIS_HOST: redis
      REDIS_PASS: $REDIS_PASS
      WEB_USER: $REDIS_WEB_USER
      WEB_PASS: $REDIS_WEB_PASS

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:skoh
    restart: always
    volumes:
      - wordpress_files:/var/lib/ftp/wordpress
    ports: ["20-21:20-21","20000-20009:20000-20009"]
    environment:
      FTP_USER: $FTP_USER
      FTP_PASS: $FTP_PASS
    #command: ["tail", "-f", "/dev/null"]

  static:
    build: ./requirements/bonus/static
    image: static:skoh
    restart: always
    ports: ["80:8000"]
    volumes: ["./requirements/bonus/static/app/public:/app/public:ro"]

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  wordpressnet:
